## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

## Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

Instructions: REPLACE the contents of this cell with descriptions of your actual datasets.

For each dataset include the following information
- Dataset #1
  - Dataset Name:
  - Link to the dataset:
  - Number of observations:
  - Number of variables:
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with repsect to the project
- Dataset #2 (if you have more than one!)
  - same as above
- etc

Each dataset deserves either a set of bullet points as above or a few sentences if you prefer that method.

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

In [ ]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [ ]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

### Dataset #1 

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [ ]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE

### Dataset #2: Hit Songs Prediction Dataset 

https://github.com/Orfium/hsp-lyrics-dataset?tab=readme-ov-file

This dataset contains data about audio features of certain songs that charted on the BillBoard Hot100 from 1942-2010. When filtering the data based on year (2000-2026), it became apparent that the dataset was missing values from what would become our "post-streaming (2013-2026)" dataset. For that reason, in order to obtains a more comprehensive dataset of BillBoard ranked songs, we filtered the BillBoard Hot100 dataset from Kaggle (described in Dataset #3). However, this dataset still has useful information about audio features for songs that ranked between 2000-2010, that could be useful when carrying out our analysis. Namely relevant features include: danceable, alternative, electronic, pop, aggressive, happy, bright, and instrumental. These features were measured on a scale from 0-1.

In [4]:
import os

if not os.path.exists("data/00-raw/hsp_lyrics_dataset.tar.gz"):
    !wget -P data/00-raw https://orfium-research-papers.s3.amazonaws.com/hit-song-prediction-dataset/hsp_lyrics_dataset.tar.gz

if not os.path.exists("data/00-raw/hsp_dataset"):
    !tar -xvzf data/00-raw/hsp_lyrics_dataset.tar.gz -C data/00-raw/

import pandas as pd

hits = pd.read_csv("data/00-raw/hsp_dataset/hsp_hits.csv")
high_level_hits = pd.read_csv("data/00-raw/hsp_dataset/high_level_hits.csv")
display(hits.columns)
display(hits.head())
display(hits.isna().sum())
display(high_level_hits.columns)
display(high_level_hits.head())
display(high_level_hits.isna().sum())

Index(['msd_id', 'echo_nest_id', 'ARTIST', 'TITLE', 'year', 'peak', 'weeks'], dtype='object')

,msd_id,echo_nest_id,ARTIST,TITLE,year,peak,weeks
0,TRMMWJS12903CBB7F5,SOLBDWO12AB0188CC2,Aerosmith,Remember (Walking In The Sand),1979,6,67
1,TRMMRUB12903CA097C,SOGDEWJ12AB0184C06,Brook Benton,Lie To Me,1986,10,13
2,TRMMFIS128E078EDEA,SOYURIX12A6701E960,Aerosmith,Cryin',1993,26,12
3,TRMMPDJ128F429472E,SOJWEBW12A8C13AEEC,Little River Band,Help Is On Its Way,1980,22,14
4,TRMMUIL128F1463720,SOSRKLH12CF5F88723,Eric Clapton,After Midnight,1970,12,18

msd_id          0
echo_nest_id    0
ARTIST          0
TITLE           0
year            0
peak            0
weeks           0
dtype: int64

Index(['msd_id', 'danceable', 'female', 'alternative', 'blues', 'electronic',
       'folkcountry', 'funksoulrnb', 'jazz', 'pop', 'raphiphop', 'rock',
       'ambient', 'dnb', 'house', 'techno', 'trance', 'cla', 'dan', 'hip',
       'jaz', 'pop.1', 'rhy', 'roc', 'spe', 'blu', 'cla.1', 'cou', 'dis',
       'hip.1', 'jaz.1', 'met', 'pop.2', 'reg', 'roc.1', 'ChaChaCha',
       'acoustic', 'aggressive', 'electronic.1', 'happy', 'not_party',
       'not_relaxed', 'not_sad', 'Cluster1', 'Cluster2', 'Cluster3',
       'Cluster4', 'Cluster5', 'bright', 'atonal', 'instrumental'],
      dtype='object')

,msd_id,danceable,female,alternative,blues,electronic,folkcountry,funksoulrnb,jazz,pop,...,not_relaxed,not_sad,Cluster1,Cluster2,Cluster3,Cluster4,Cluster5,bright,atonal,instrumental
0,TRMMWJS12903CBB7F5,0.528196,0.214136,0.076715,0.088353,0.094057,0.127020,0.067153,0.057225,0.052493,...,0.780863,0.689657,0.110400,0.253374,0.175422,0.328600,0.132204,0.909691,0.101535,0.162628
1,TRMMRUB12903CA097C,0.982040,0.972055,0.057513,0.129689,0.162842,0.162846,0.011860,0.025092,0.100032,...,0.314300,0.578807,0.121474,0.118074,0.591957,0.122679,0.045816,0.087996,0.931372,0.000347
2,TRMMFIS128E078EDEA,0.313940,0.052508,0.248732,0.034915,0.030114,0.054675,0.006778,0.014800,0.155980,...,0.989100,0.720970,0.210789,0.180598,0.450649,0.083385,0.074579,0.995537,0.020812,0.003392
3,TRMMPDJ128F429472E,0.300077,0.267567,0.095285,0.191411,0.032080,0.268002,0.026606,0.207616,0.099850,...,0.245614,0.134404,0.107497,0.122557,0.640115,0.119482,0.010349,0.959430,0.454213,0.019033
4,TRMMUIL128F1463720,0.178557,0.313151,0.084556,0.061396,0.014255,0.276597,0.010919,0.029266,0.086664,...,0.745764,0.784257,0.274149,0.272222,0.199427,0.204986,0.049216,0.999994,0.001774,0.011261

msd_id          0
danceable       0
female          0
alternative     0
blues           0
electronic      0
folkcountry     0
funksoulrnb     0
jazz            0
pop             0
raphiphop       0
rock            0
ambient         0
dnb             0
house           0
techno          0
trance          0
cla             0
dan             0
hip             0
jaz             0
pop.1           0
rhy             0
roc             0
spe             0
blu             0
cla.1           0
cou             0
dis             0
hip.1           0
jaz.1           0
met             0
pop.2           0
reg             0
roc.1           0
ChaChaCha       0
acoustic        0
aggressive      0
electronic.1    0
happy           0
not_party       0
not_relaxed     0
not_sad         0
Cluster1        0
Cluster2        0
Cluster3        0
Cluster4        0
Cluster5        0
bright          0
atonal          0
instrumental    0
dtype: int64

In [5]:
hits_filtered = hits[
    (hits["year"].between(2000, 2026)) &
    (hits["peak"].between(1, 3))
]
hits_filtered.shape

(96, 7)

In [6]:
display(hits["year"].min())
display(hits["year"].max())

1942

2010

In [7]:
hits_2000_2013 = hits_filtered[
    (hits_filtered["year"] >= 2000) &
    (hits_filtered["year"] <= 2013)
]

hits_2000_2013.shape

(96, 7)

In [8]:
hits_2013_2026 = hits_filtered[
    (hits_filtered["year"] > 2013) &
    (hits_filtered["year"] <= 2026)
]
hits_2013_2026.shape

(0, 7)

In [9]:
hits_2000_2013.to_csv("data/02-processed/hsp_hits_2000_2013.csv", index=False)
hits_2013_2026.to_csv("data/02-processed/hsp_hits_2013_2026.csv", index=False)

### Dataset #3: BillBoard Hot100 Dataset

https://www.kaggle.com/datasets/ludmin/billboard?select=hot100.csv

This dataset comprises comprehensive data about every song that has ever charted on the BillBoard Hot100 (since 1958), including song title, artist, rank (from 1-100), position peaked on the Hot100 (from 1-100), number of weeks on the Hot 100, date the song got ranked on the chart, and the song's release date. This dataset is the most up-to-date one of BillBoard chart data, but instead of going up to January/February 2026, its last recorded data ends at October 2025. For the purposes of this data analysis, however, we will generalize the conclusions from song post 2014 to October 2025 to be part of our "post-streaming (2013-2026)" dataset, due to the large size of the dataset compared to the relatively small time period of missing values. 

The dataset has been filtered below for the appropriate years (2000-2026), and divided into separate dataframes (hot100_2000_2013_sorted, and hot100_2014_2026_sorted) sorted based on year, month, and chart rank. It contains 2190 data points for songs charted between 2000-2013, and 1851 data points for songs charted between 2014-2026. This accounts for the fact that more than three songs chart in the top three ranks in any given month. There are no missing or null values recorded for any songs.

In [21]:
!pip install kagglehub[pandas-datasets]
import kagglehub

kagglehub.dataset_download(
    "ludmin/billboard",
    path="hot100.csv",
    output_dir="./data/00-raw"
)

Defaulting to user installation because normal site-packages is not writeable
Collecting kagglehub[pandas-datasets]
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 kB 2.4 MB/s eta 0:00:00
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub[pandas-datasets])
  Downloading kagglesdk-0.1.15-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from kagglehub[pandas-datasets]) (24.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.11/site-packages (from kagglehub[pandas-datasets]) (6.0.1)
Requirement already satisfied: requests in /home/esshah/.local/lib/python3.11/site-packages (from kagglehub[pandas-datasets]) (2.32.5)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from kagglehub[pandas-datasets]) (4.66.2)
Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (from kagglehub[pandas-datasets]) (2.2.3)
Requirement already satisfied: protobuf in /opt/conda/lib/python3.11/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub[pandas-datasets]) (4.25.3)
Requirement already satisfied: numpy>=1.23.2 in /opt/conda/lib/python3.11/site-packages (from pandas->kagglehub[pandas-datasets]) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas->kagglehub[pandas-datasets]) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas->kagglehub[pandas-datasets]) (2024.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->kagglehub[pandas-datasets]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->kagglehub[pandas-datasets]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->kagglehub[pandas-datasets]) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->kagglehub[pandas-datasets]) (2024.8.30)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.16.0)
Downloading kagglesdk-0.1.15-py3-none-any.whl (160 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.4/160.4 kB 8.6 MB/s eta 0:00:00
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 6.1 MB/s eta 0:00:00
Installing collected packages: kagglesdk, kagglehub
Successfully installed kagglehub-1.0.0 kagglesdk-0.1.15
Downloading to ./data/00-raw/hot100.csv...

100%|██████████| 34.8M/34.8M [00:01<00:00, 20.2MB/s]

'./data/00-raw/hot100.csv'

In [12]:
import pandas as pd
hot100 = pd.read_csv("data/00-raw/hot100.csv")
hot100["release_date"] = pd.to_datetime(hot100["Date"])

hot100["year"] = hot100["release_date"].dt.year
hot100["month"] = hot100["release_date"].dt.month

hot100_filtered = hot100[
    (hot100["year"].between(2000, 2026)) &
    (hot100["Rank"].between(1, 3))
]
display(hot100_filtered.shape)
display(hot100.isna().sum())

/tmp/ipykernel_415/2927359384.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  hot100 = pd.read_csv("data/00-raw/hot100.csv")

(4041, 11)

Date               0
Song               0
Artist             0
Rank               0
Last Week          0
Peak Position      0
Weeks in Charts    0
Image URL          0
release_date       0
year               0
month              0
dtype: int64

In [13]:
hot100_2000_2013 = hot100_filtered[hot100_filtered["year"] <= 2013]
hot100_2000_2013.shape

(2190, 11)

In [14]:
hot100_2014_2026 = hot100_filtered[hot100_filtered["year"] >= 2014]
hot100_2014_2026.shape

(1851, 11)

In [15]:
hot100_2000_2013_sorted = hot100_2000_2013.sort_values(
    by=["year", "month", "Rank"]
)
hot100_2000_2013_sorted

,Date,Song,Artist,Rank,Last Week,Peak Position,Weeks in Charts,Image URL,release_date,year,month
216087,2000-01-05,Smooth,Santana Featuring Rob Thomas,1,1,1,24,#,2000-01-05,2000,1
216187,2000-01-12,What A Girl Wants,Christina Aguilera,1,11,1,8,#,2000-01-12,2000,1
216287,2000-01-19,What A Girl Wants,Christina Aguilera,1,1,1,9,#,2000-01-19,2000,1
216387,2000-01-26,I Knew I Loved You,Savage Garden,1,2,1,15,#,2000-01-26,2000,1
216088,2000-01-05,Back At One,Brian McKnight,2,2,2,20,#,2000-01-05,2000,1
...,...,...,...,...,...,...,...,...,...,...,...
288988,2013-12-25,Timber,Pitbull Featuring Ke$ha,2,2,2,10,#,2013-12-25,2013,12
288689,2013-12-04,Wrecking Ball,Miley Cyrus,3,3,1,14,#,2013-12-04,2013,12
288789,2013-12-11,Royals,Lorde,3,1,1,22,#,2013-12-11,2013,12
288889,2013-12-18,Counting Stars,OneRepublic,3,5,3,25,#,2013-12-18,2013,12
288989,2013-12-25,Counting Stars,OneRepublic,3,3,3,26,#,2013-12-25,2013,12

In [16]:
hot100_2014_2026_sorted = hot100_2014_2026.sort_values(
    by=["year", "month", "Rank"]
)
hot100_2014_2026_sorted

,Date,Song,Artist,Rank,Last Week,Peak Position,Weeks in Charts,Image URL,release_date,year,month
289087,2014-01-01,The Monster,Eminem Featuring Rihanna,1,1,1,8,#,2014-01-01,2014,1
289187,2014-01-08,The Monster,Eminem Featuring Rihanna,1,1,1,9,#,2014-01-08,2014,1
289287,2014-01-15,Timber,Pitbull Featuring Ke$ha,1,2,1,13,#,2014-01-15,2014,1
289387,2014-01-22,Timber,Pitbull Featuring Ke$ha,1,1,1,14,#,2014-01-22,2014,1
289487,2014-01-29,Timber,Pitbull Featuring Ke$ha,1,1,1,15,#,2014-01-29,2014,1
...,...,...,...,...,...,...,...,...,...,...,...
350688,2025-10-22,Opalite,Taylor Swift,2,2,2,2,#,2025-10-22,2025,10
350389,2025-10-01,Soda Pop,Saja Boys: Andrew Choi| Neckwav| Danny Chung| ...,3,5,3,13,#,2025-10-01,2025,10
350489,2025-10-08,Tit For Tat,Tate McRae,3,3,1,-,#,2025-10-08,2025,10
350589,2025-10-15,Elizabeth Taylor,Taylor Swift,3,3,1,-,#,2025-10-15,2025,10
350689,2025-10-22,Golden,HUNTR/X: EJAE| Audrey Nuna & REI AMI,3,13,1,17,#,2025-10-22,2025,10

In [17]:
hot100_2000_2013_sorted.to_csv("data/02-processed/bb_hot100_2000_2013.csv", index=False)
hot100_2014_2026_sorted.to_csv("data/02-processed/bb_hot100_2014_2026.csv", index=False)

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them